trigger: none

parameters:
  - name: suffix
    type: string
    default: 'd'

resources:
  pipelines:
  - pipeline: CI-Pipeline
    source: CI
    trigger: 
      branches:
      - develop
      - release/*

variables:
  - name: deploymentFolderName
    value: 'Deployment'
  - name: ciArtifactName
    value: 'build'
  - name: dockerFilePath
    value: '$(Build.SourcesDirectory)/DockerApp/Dockerfile'
  - name: buildTag
    value: '$(resources.pipeline.CI-Pipeline.runID)'
  - name: agentImageName
    value: 'ubuntu-latest'
  - name: dockerImageName
    value: 'azurerecipe'

  - name: resourceNamePrefix
    value: 'customer-project'
  - name: resourceNameSuffix
    value: 'build'
  - name: resourceGroupName
    value: '$(resourceNamePrefix)-$(resourceNameSuffix)'
  - name: resourceLocation
    value: 'westeurope'
  - name: containerRegistryLoginServer
    value: 'azurerecipes.azurecr.io'
  - name: containerRegistryUsername
    value: 'azurerecipes'
  - name: containerRegistryPassword
    value: 'abc123'

  - name: containerRegistryServiceConnection
    value: 'Container Registry Connection'
  - name: armServiceConnection
    value: 'ARM Service Connection'

  - name: currentDate
    value: '$[format(''{0:yyyy}-{0:MM}-{0:dd}'', pipeline.startTime)]'

stages:
  - stage: deployDevEnvironment
    displayName: 'Deploy Dev Environment'
    dependsOn: []
    jobs:
      - deployment: deploy_docker_image
        displayName: 'Deploy Container Instance with Image'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: 'Create Resource Group'
                  inputs:
                    azureSubscription: '$(armServiceConnection)'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az group create --location $(resourceLocation) --name $(resourceGroupName) --tags 'DeployedAt=$(currentDate)' 'DeployedBy=$(Build.RequestedFor)' 'DeployedFrom=$(System.TeamProject)'

                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Deploy ARM Template (ResourceGroup)'
                  inputs:
                    azureResourceManagerConnection: '$(armServiceConnection)'
                    resourceGroupName: '$(resourceGroupName)'
                    location: '$(resourceLocation)'
                    csmFile: '$(Pipeline.Workspace)/CI-Pipeline/$(ciArtifactName)/$(deploymentFolderName)/azuredeploy.instance.bicep'
                    overrideParameters: '-resourceNamePrefix "$(resourceNamePrefix)" -resourceNameSuffix "$(resourceNameSuffix)" -containerRegistryLoginServer "$(containerRegistryLoginServer)" -containerRegistryUsername "$(containerRegistryUsername)" -containerRegistryPassword "$(containerRegistryPassword)" -dockerImageName "$(dockerImageName)" -dockerImageTag "$(buildTag)"'
                    deploymentMode: 'Incremental'
                    deploymentName: 'Customer-Project-$(Build.BuildId)-$(Environment.Name)'